export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const ADD_TO_SEEN = 'ADD_TO_SEEN';
export const FETCH_WATCHLIST_MOVIES = 'FETCH_WATCHLIST_MOVIES';
export const FETCH_SEEN_MOVIES = 'FETCH_SEEN_MOVIES';
